### PR TITLE
feat: add multiple requests function

### PR DESCRIPTION
**Pull request by cd**
`Resources.ContentLoaderExtended.ExecuteHttpRequests` for calling multiple `ExecuteHttpRequest` without blocking.

### CODE REVIEW

**Review by stefan-lacatus — APPROVED** [review]
I like and approve of this.

Just out of curiosity, what is the use case that caused this need?

**Comment by stefan-lacatus** [comment]
I'll release 2.1.0 tomorrow with this change. Thanks!

**Comment by cd** [comment]
> I like and approve of this.
> 
> Just out of curiosity, what is the use case that caused this need?

Thanks, that's great to hear!

You need this, for example, if you want to execute several HTTP requests in a TWX service to collect information from different sources. Usually, the requests are executed one after the other, which can take a long time if there are a certain number of requests.

image

**Comment by stefan-lacatus** [comment]
https://github.com/ptc-iot-sharing/ContentLoaderExtendedTWX/releases/tag/v2.1.0 is out. Thanks!

**Pull request merged**
